### ISSUE TITLE
Problem with setting connection timeout

### ISSUE THREAD

**Issue by rjsvaljean** [susestudio/studio_api#3]
There seems to be an error with setting the connection timeout. The current assignment (studio_api/lib/connection.rb:66) sets it to `x.to_i || 45` which translates to 0||45 if x is not set. Hence the default timeout is set to 0 instead of 45 which should be the default value.

Possible solution:

<pre>
diff --git a/lib/studio_api/connection.rb b/lib/studio_api/connection.rb
index 30ed340..d9772ae 100644
--- a/lib/studio_api/connection.rb
+++ b/lib/studio_api/connection.rb
@@ -63,7 +63,7 @@ module StudioApi
       @password = password
       self.uri = uri
       self.proxy = options[:proxy] #nil as default is OK
-      @timeout = options[:timeout].to_i || 45
+      @timeout = options[:timeout] ? options[:timeout].to_i : 45
       @ssl = options[:ssl] || { :verify_mode => OpenSSL::SSL::VERIFY_NONE } # don't verify as default
     end
</pre>

**Comment by bmaland** [comment]
Thanks for your bug report, I fixed this in my fork. Should be pulled into mainline soon enough. :)

**Comment by jreidinger** [comment]
Yes, good observation. Thanks for report and for fix. bmaland if flavio will have problem with merging your branch, just contact me. Thanks

**Comment by rjsvaljean** [comment]
Is it possible to push out a new version of this gem to rubygems including this patch. IMO the bug is important enough to warrant a minor version bump. I'm working on a gem that uses this one. It would be very useful to have a version of the gem with this bug fixed.

Thanks.

**Comment by flavio** [comment]
I've just released v3.1.2 on gemcutter.
Packages are being built on obs inside of the devel:languages:ruby:extensions repository.
